###
GET http://localhost:8888/service-publication-microservice/default

###
GET http://localhost:8083/actuator/health

###
GET http://localhost:8083/actuator/prometheus

###
GET http://localhost:8083/services

###
GET http://localhost:8083/services/accommodation

###
GET http://localhost:8083/services/food

###
GET http://localhost:8083/services/transportation

###
GET http://localhost:8083/services/supplier/6a965c40-81ec-4dd1-a68c-17d8ab43b13e

##Usando security, es decir el gateway

@host = http://localhost:8080

### Customer Login
# @name login
POST {{host}}/keycloak-server/realms/ecommerce/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=turismo&username=supplier2&password=supplier2

###
@token = {{login.response.body.$.access_token}}

GET {{host}}/service-publication-microservice/services
Authorization: Bearer {{token}}