###
GET http://localhost:8888/service-publication-microservice/default

###
GET http://localhost:8083/actuator/health

###
GET http://localhost:8083/actuator/prometheus

###
GET http://localhost:8086/services/location

###
GET http://localhost:8083/services/accommodation

###
GET http://localhost:8086/types/food

###
GET http://localhost:8083/services/transportation

###
GET http://localhost:8083/services/supplier/6a965c40-81ec-4dd1-a68c-17d8ab43b13e

##Usando security, es decir el gateway

@host = http://localhost:8080

### Customer Login
# @name login
POST {{host}}/keycloak-server/realms/ecommerce/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=turismo&username=supplier2&password=supplier2

###
@token = {{login.response.body.$.access_token}}

GET {{host}}/service-publication-microservice/services
Authorization: Bearer {{token}}

###prueba cola de kafka
< {%
    now = new Date();
    instantStart = now.toISOString();
    instantEnd = now.setMonth(now.getMonth() + 1);
    request.variables.set("instantStart", instantStart);
    request.variables.set("instantEnd", instantEnd);
%}
POST http://localhost:8083/services/food
Content-Type: application/json

{
  "name": "Comida rápida llevada directamente a tu hotel",
  "description": "Transporte a las montañas",
  "unitValue": 49990,
  "destination": {
    "id": 10,
    "address": "Suite 372 0812 Crysta Mill, Mariahfurt, LA 43111",
    "latitude": 87.34822841,
    "longitude": 112.47083979,
    "country": "Fiji",
    "city": "East Larryview",
    "municipality": "Montana"
  },
  "startDate": "2024-10-02T10:15:30Z",
  "endDate": "2024-10-02T18:00:00Z",
  "supplierId": "6a965c40-81ec-4dd1-a68c-17d8ab43b13e",
  "foodType": {
    "foodTypeId": 3,
    "name": "DINNER"
  }
}