spring:
  application:
    # Never use '_' in application name
    # Use '-' instead
    # Otherwise gateway may not work correctly
    name: service-publication-microservice

  config:
    import: configserver:http://localhost:8888

  # Message queue
  cloud:
    stream:
      kafka:
        binder:
          # Kafka server URL
          # 9092 is the default port of Kafka
          brokers: localhost:9092
      bindings:
        # https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/functional-binding-names.htm
        # Format: <method name>-<in or out>-<index>
        # sendServices: name of the method that sends the message
        # out: because is a consumer
        # 0: Index of the binding. This makes sense when the same method sends to multiple queues
        sendServices-out-0:
          # Name of the queue that will manage the messages
          destination: query-services-queue
        sendServiceTypes-out-0:
          # Name of the queue that will manage the messages
          destination: query-types-queue
        sendLocation-out-0:
          # Name of the queue that will manage the messages
          destination: query-locations-queue
  datasource:
    url: jdbc:mysql://10.43.101.202:3306/services
    username: kevinevelasco
    password: kevinevelasco
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
springdoc:
  pathsToMatch: /api/**
  swagger-ui:
    path: /api-docs


